## POWERLINE configuration
set -g default-terminal "screen-256color"
source "/usr/share/powerline/bindings/tmux/powerline.conf"

## CONFIGURAZIONI
# CTRL + A   ?     lista comandi (incl. rimappature)

# remap prefix da 'CTRL-b' a 'CTRL-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Split h e v con i tasti - e _
bind _ split-window -h
bind - split-window -v
unbind '"'
unbind %

# Selector for Copy and Paste
bind c copy-mode
bind v paste-buffer
#CTRL+ space per selezionare muovendosi
bind-key -T copy-mode C-c send-keys -X copy-selection-and-cancel
bind-key -T copy-mode C-x send-keys -X cancel

# Resize
bind i resize-pane -U 3
bind j resize-pane -L 3
bind k resize-pane -D 3
bind l resize-pane -R 3

# Windows
bind-key -T prefix w choose-tree -w
bind-key -T prefix n new-window

# Panes
bind-key -T prefix z resize-pane -Z